"""HTML report template renderer."""

from __future__ import annotations

from collections import defaultdict
from html import escape
from typing import Dict, List

from src.templates.company_outline import default_company_outline


def render_html_report(
    claims: List[dict],
    charts: List[dict] | None = None,
    title: str = "Company Research Report",
) -> str:
    charts = charts or []
    by_section: Dict[str, List[dict]] = defaultdict(list)
    for claim in claims:
        by_section[str(claim.get("section_name", "unknown"))].append(claim)

    section_html: List[str] = []
    for section in default_company_outline():
        name = section["section_name"]
        header = escape(section["section_title"])
        section_html.append(f"<section><h2>{header}</h2>")
        section_claims = by_section.get(name, [])
        if not section_claims:
            section_html.append("<p>No claims available for this section.</p></section>")
            continue

        section_html.append("<ul>")
        for item in section_claims:
            claim_text = escape(str(item.get("claim_text", "")))
            confidence = float(item.get("confidence", 0.0))
            evidence_ids = ", ".join([escape(str(x)) for x in item.get("evidence_ids", [])])
            section_html.append("<li>")
            section_html.append(f"<p>{claim_text}</p>")
            if evidence_ids:
                section_html.append(f"<p><small>evidence_ids: {evidence_ids}</small></p>")
            section_html.append(f"<p><small>confidence: {confidence:.2f}</small></p>")
            section_html.append("</li>")
        section_html.append("</ul></section>")

    chart_html = ["<section><h2>Charts</h2>"]
    if charts:
        chart_html.append("<ul>")
        for chart in charts:
            chart_html.append(
                f"<li>{escape(str(chart.get('title', 'Untitled')))}: "
                f"<code>{escape(str(chart.get('output_path', '')))}</code></li>"
            )
        chart_html.append("</ul>")
    else:
        chart_html.append("<p>No charts generated.</p>")
    chart_html.append("</section>")

    body = "\n".join(section_html + chart_html)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 24px; line-height: 1.5; }}
    h1, h2 {{ margin: 0 0 12px 0; }}
    section {{ margin: 24px 0; padding: 12px 16px; border: 1px solid #ddd; border-radius: 6px; }}
    ul {{ margin: 0; padding-left: 20px; }}
    p {{ margin: 6px 0; }}
    small {{ color: #555; }}
    code {{ background: #f6f6f6; padding: 1px 4px; border-radius: 4px; }}
  </style>
</head>
<body>
  <h1>{escape(title)}</h1>
  <p>Generated by Open DeepReport++ Stage 10 export template.</p>
  {body}
</body>
</html>"""

