"""Markdown report template renderer."""

from __future__ import annotations

from collections import defaultdict
from typing import Dict, List

from src.templates.company_outline import default_company_outline


def render_markdown_report(
    claims: List[dict],
    charts: List[dict] | None = None,
    title: str = "Company Research Report",
) -> str:
    charts = charts or []
    by_section: Dict[str, List[dict]] = defaultdict(list)
    for claim in claims:
        by_section[str(claim.get("section_name", "unknown"))].append(claim)

    lines: List[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("Generated by Open DeepReport++ Stage 10 export template.")
    lines.append("")

    for section in default_company_outline():
        name = section["section_name"]
        title = section["section_title"]
        lines.append(f"## {title}")
        lines.append("")
        section_claims = by_section.get(name, [])
        if not section_claims:
            lines.append("- No claims available for this section.")
            lines.append("")
            continue

        for item in section_claims:
            claim_text = str(item.get("claim_text", "")).strip()
            confidence = float(item.get("confidence", 0.0))
            evidence_ids = list(item.get("evidence_ids", []))
            lines.append(f"- {claim_text}")
            if evidence_ids:
                lines.append(f"  - evidence_ids: {', '.join(evidence_ids)}")
            lines.append(f"  - confidence: {confidence:.2f}")
        lines.append("")

    lines.append("## Charts")
    lines.append("")
    if charts:
        for chart in charts:
            lines.append(f"- {chart.get('title', 'Untitled')}: `{chart.get('output_path', '')}`")
    else:
        lines.append("- No charts generated.")
    lines.append("")

    return "\n".join(lines)

