import json
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

import yaml

from src.app.pipeline import run_pipeline
from src.agents.writer import Writer
from src.schemas.claim import ClaimItem


def _plan():
    return [
        {"section_name": "executive_summary", "section_title": "Executive Summary"},
        {"section_name": "financial_analysis", "section_title": "Financial Analysis"},
    ]


def _claims():
    return [
        ClaimItem(
            claim_id="cl_1",
            section_name="financial_analysis",
            claim_text="Revenue improved.",
            evidence_ids=["ev_1"],
            numeric_values={"revenue_billion": 1.0},
            risk_level="low",
            confidence=0.8,
            notes="",
        )
    ]


class _OkHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        length = int(self.headers.get("Content-Length", "0"))
        payload = json.loads(self.rfile.read(length).decode("utf-8"))
        claims = payload.get("claims", [])
        evidence_ids = []
        if claims and isinstance(claims[0], dict):
            evidence_ids = list(claims[0].get("evidence_ids", []))
        text = "# Remote Report\n\n" + f"- evidence_ids: {', '.join(evidence_ids)}\n"
        body = json.dumps({"text": text}).encode("utf-8")

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format, *args):
        del format, args


class _ErrorHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        self.send_response(500)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(b'{"error":"server failure"}')

    def log_message(self, format, *args):
        del format, args


def _start_server(handler_cls):
    server = HTTPServer(("127.0.0.1", 0), handler_cls)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    return server, thread


def _write_backend_config(path: Path, base_url: str, timeout: float = 3.0, retry: int = 0):
    payload = {
        "writer_backend": {
            "mode": "remote",
            "common": {
                "timeout": timeout,
                "retry": retry,
                "max_tokens": 256,
                "temperature": 0.1,
            },
            "backends": {
                "remote": {
                    "model_name": "unit-test-remote",
                    "base_url": base_url,
                }
            },
        }
    }
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def test_backend_generate_remote_success(tmp_path: Path):
    server, thread = _start_server(_OkHandler)
    try:
        cfg_path = tmp_path / "model_backends.yaml"
        base_url = f"http://127.0.0.1:{server.server_port}/generate"
        _write_backend_config(cfg_path, base_url)

        writer = Writer(
            mode="backend_generate",
            backend="remote",
            backend_config_path=str(cfg_path),
            debug_output_path=str(tmp_path / "writer_debug.json"),
        )
        report = writer.render_markdown(_plan(), _claims())
        debug = json.loads((tmp_path / "writer_debug.json").read_text(encoding="utf-8"))

        assert "# Remote Report" in report
        assert "ev_1" in report
        assert debug["fallback_triggered"] is False
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=1)


def test_backend_generate_fallback_on_remote_error(tmp_path: Path):
    server, thread = _start_server(_ErrorHandler)
    try:
        cfg_path = tmp_path / "model_backends.yaml"
        base_url = f"http://127.0.0.1:{server.server_port}/generate"
        _write_backend_config(cfg_path, base_url, timeout=1.0, retry=0)

        writer = Writer(
            mode="backend_generate",
            backend="remote",
            backend_config_path=str(cfg_path),
            debug_output_path=str(tmp_path / "writer_debug.json"),
        )
        report = writer.render_markdown(_plan(), _claims())
        debug = json.loads((tmp_path / "writer_debug.json").read_text(encoding="utf-8"))

        assert "This report is generated by a claim-first Stage 4 pipeline." in report
        assert "ev_1" in report
        assert debug["fallback_triggered"] is True
        assert debug["error_message"]
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=1)


def test_stage11b_pipeline_report_non_empty(tmp_path: Path):
    server, thread = _start_server(_OkHandler)
    try:
        cfg_path = tmp_path / "model_backends.yaml"
        base_url = f"http://127.0.0.1:{server.server_port}/generate"
        _write_backend_config(cfg_path, base_url, timeout=2.0, retry=0)

        output_dir = tmp_path / "outputs"
        report_dir = tmp_path / "reports"
        result = run_pipeline(
            output_dir=str(output_dir),
            report_dir=str(report_dir),
            writer_mode="backend_generate",
            writer_backend="remote",
            writer_backend_config_path=str(cfg_path),
            writer_debug_path=str(report_dir / "writer_debug.json"),
        )

        report_path = Path(result["report_markdown"])
        debug_path = Path(result["writer_debug"])
        assert report_path.exists()
        assert report_path.read_text(encoding="utf-8").strip()
        assert debug_path.exists()
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=1)
