from src.agents.writer import Writer
from src.schemas.claim import ClaimItem


def _plan():
    return [
        {"section_name": "executive_summary", "section_title": "Executive Summary"},
        {"section_name": "financial_analysis", "section_title": "Financial Analysis"},
    ]


def _claims():
    return [
        ClaimItem(
            claim_id="cl_1",
            section_name="financial_analysis",
            claim_text="Revenue improved.",
            evidence_ids=["ev_1"],
            numeric_values={"revenue_billion": 1.0},
            risk_level="low",
            confidence=0.8,
            notes="",
        )
    ]


def test_writer_backend_generate_mock():
    writer = Writer(mode="backend_generate", backend="mock")
    markdown = writer.render_markdown(_plan(), _claims())
    assert "Generated by backend: mock" in markdown


def test_writer_backend_generate_fallback_to_template():
    writer = Writer(mode="backend_generate", backend="local_small")
    markdown = writer.render_markdown(_plan(), _claims())
    assert "This report is generated by a claim-first Stage 4 pipeline." in markdown

