"""Mock generation backend for local/offline development."""

from __future__ import annotations

from collections import defaultdict
from typing import Any, Dict, List

from src.generation.backend_base import GenerationBackend
from src.schemas.claim import ClaimItem


class MockGenerationBackend(GenerationBackend):
    def __init__(self, **_: Any):
        pass

    @property
    def name(self) -> str:
        return "mock"

    def generate_text(self, prompt: str, **kwargs: Any) -> str:
        del prompt
        plan: List[dict] = list(kwargs.get("plan", []))
        claims: List[ClaimItem] = list(kwargs.get("claims", []))

        by_section: Dict[str, List[ClaimItem]] = defaultdict(list)
        for claim in claims:
            by_section[claim.section_name].append(claim)

        lines: List[str] = []
        lines.append("# Company Research Report")
        lines.append("")
        lines.append("Generated by backend: mock")
        lines.append("")

        for section in plan:
            title = section["section_title"]
            name = section["section_name"]
            lines.append(f"## {title}")
            lines.append("")
            section_claims = by_section.get(name, [])
            if not section_claims:
                lines.append("- No claims generated for this section in current sample.")
                lines.append("")
                continue
            for item in section_claims:
                lines.append(f"- {item.claim_text}")
                if item.evidence_ids:
                    lines.append(f"  - evidence_ids: {', '.join(item.evidence_ids)}")
                lines.append(f"  - confidence: {item.confidence:.2f}")
            lines.append("")

        return "\n".join(lines)

    def generate_structured(
        self,
        prompt: str,
        schema: Dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> Dict[str, Any]:
        text = self.generate_text(prompt=prompt, **kwargs)
        return {
            "backend": self.name,
            "schema_used": bool(schema),
            "text": text,
        }
